### PR TITLE
Bc asset updates

### PR DESCRIPTION
**Pull request by SGBM-Jimbo**
##  [ZAU-68]

---

### Summary

Updates the assets to local files. The 404 f14 and logo on please wait page. Adds Exemption to dashboard for LOA users. Also updates the activity date to the end of the month of the next month if you have time. If you do not have time then your expiration date is the month you did not meet the 1 hour requirement.

---

### DB Changes (if any)

- [] What is the change?

```
None
```

---

### Testing

1. Run all tests.
2. Additional testing requirements...

--- 
Checking 404 and Load icon is easy. You have to create a user on LOA to check the exemption part and the month requirement requires database access to modify information.

### Post-Deployment Validation

How to verify in the production environment.

---

### CODE REVIEW

**Review by bkinney272 — COMMENTED** [review]
ok

**Review by bkinney272 — APPROVED** [review]
ok

**Comment by callie0923** [comment]
> ok

Who are you?

**Review by callie0923 — APPROVED** [review]
LGTM!

**Pull request merged**
